ignore:
  - "lib/stove-testing-e2e/src/main/kotlin/com/trendyol/stove/functional"
  - "lib/stove-testing-e2e/src/main/kotlin/com/trendyol/stove/testing/e2e/system/abstractions"
  - "lib/stove-testing-e2e/src/main/kotlin/com/trendyol/stove/testing/e2e/system/annotations"
  - "lib/stove-testing-e2e/src/main/kotlin/com/trendyol/stove/testing/e2e/serialization"
  - "examples/spring-example"
  - "examples/spring-standalone-example"
  - "examples/ktor-example"
