ignore:
  - "lib/stove/src/main/kotlin/com/trendyol/stove/functional"
  - "lib/stove/src/main/kotlin/com/trendyol/stove/system/abstractions"
  - "lib/stove/src/main/kotlin/com/trendyol/stove/system/annotations"
  - "lib/stove/src/main/kotlin/com/trendyol/stove/serialization"
  - "examples/ktor-example"
  - "examples/micronaut-example"
  - "examples/spring-4x-example"
  - "examples/spring-example"
  - "examples/spring-standalone-example"
  - "examples/spring-streams-example"
  - "test-extensions/stove-extensions-kotest/src/test"
  - "test-extensions/stove-extensions-junit/src/test"
  - "recipes/"
