dependencies {
  implementation(projects.shared.domain)
  implementation(projects.shared.application)
  implementation(libs.ktor.server.core.jvm)
  implementation(libs.ktor.server.netty.jvm)
  implementation(libs.ktor.server.content.negotiation.jvm)
  implementation(libs.ktor.server.statuspages)
  implementation(libs.ktor.server.callLogging)
  implementation(libs.ktor.server.callId)
  implementation(libs.ktor.server.conditionalHeaders)
  implementation(libs.ktor.server.cors)
  implementation(libs.ktor.server.defaultHeaders)
  implementation(libs.ktor.server.cachingHeaders)
  implementation(libs.ktor.server.autoHeadResponse)
  implementation(libs.ktor.server.config.yml)
  implementation(libs.ktor.swagger.ui)
  implementation(libs.ktor.serialization.jackson.json)
  implementation(libs.koin)
  implementation(libs.koin.ktor)
  implementation(libs.slf4j.api)
  implementation(libs.arrow.core)
  implementation(libs.hoplite)
  implementation(libs.hoplite.yaml)
  implementation(libs.logback.classic)
  implementation(libs.ktor.client.core)
  implementation(libs.ktor.client.cio)
  implementation(libs.ktor.client.plugins.logging)
  implementation(libs.ktor.client.content.negotiation)
  implementation(libs.kotlinFpUtil)
  implementation(libs.kotlin.logging.jvm)
  implementation(libs.kediatr.koin)

  implementation(libs.exposed.core)
  implementation(libs.exposed.r2dbc)
  implementation(libs.exposed.json)
  implementation(libs.exposed.javaTime)
  implementation(libs.postgresql.r2dbc)
  implementation(libs.postgresql)
  implementation(libs.r2dbc.pool)
  implementation(libs.flyway.core)
  implementation(libs.flyway.database.postgresql)

  implementation(libs.kafkaKotlin)
}

dependencies {
  testImplementation(libs.stove.testing)
  testImplementation(libs.stove.testing.postgresql)
  testImplementation(libs.stove.testing.http)
  testImplementation(libs.stove.testing.wiremock)
  testImplementation(libs.stove.testing.kafka)
  testImplementation(libs.stove.ktor.testing)
}
