server:
  port: 8080
couchbase:
  bucket: stove-java-spring-boot
  hosts: localhost
  username: Administrator
  password: password
  timeout: 30
kafka:
  bootstrap-servers: localhost:9092
  group-id: stove-java-spring-boot
  heartbeat-interval-seconds: 2
  request-timeout-seconds: 30
  session-timeout-seconds: 10
  auto-create-topics: true
  auto-offset-reset: earliest
  interceptor-classes: [ ]
  topics:
    product:
      name: ${kafka.group-id}.product
      retry: ${kafka.topic.product}.retry
      dead-letter: ${kafka.topic.product}.error
external-apis:
  category:
    url: http://localhost:9091
    timeout: 30
