import { EVENT_TYPE, type EventType, type LivePayloads } from "./types";
import {
  isBoolean,
  isNullableNumber,
  isNullableString,
  isNumber,
  isRunStatus,
  isSpanStatus,
  isStatus,
  isString,
  isStringArray,
  isStringRecord,
  type ObjectSchema,
} from "./validation";

export const payloadSchemas = {
  [EVENT_TYPE.RUN_STARTED]: {
    app_name: isString,
    started_at: isString,
    stove_version: isNullableString,
    systems: isStringArray,
    metadata: isStringRecord,
  },
  [EVENT_TYPE.RUN_ENDED]: {
    ended_at: isString,
    status: isRunStatus,
    total_tests: isNumber,
    passed: isNumber,
    failed: isNumber,
    duration_ms: isNumber,
  },
  [EVENT_TYPE.TEST_STARTED]: {
    test_id: isString,
    test_name: isString,
    spec_name: isString,
    test_path: isStringArray,
    started_at: isString,
    status: isStatus,
  },
  [EVENT_TYPE.TEST_ENDED]: {
    test_id: isString,
    status: isStatus,
    duration_ms: isNumber,
    error: isNullableString,
    ended_at: isString,
  },
  [EVENT_TYPE.ENTRY_RECORDED]: {
    id: isNumber,
    test_id: isString,
    timestamp: isString,
    system: isString,
    action: isString,
    result: isStatus,
    input: isNullableString,
    output: isNullableString,
    metadata: isNullableString,
    expected: isNullableString,
    actual: isNullableString,
    error: isNullableString,
    trace_id: isNullableString,
    assertion_id: isString,
    attempt_count: isNumber,
    failure_count: isNumber,
  },
  [EVENT_TYPE.SPAN_RECORDED]: {
    id: isNumber,
    test_id: isNullableString,
    trace_id: isString,
    span_id: isString,
    parent_span_id: isNullableString,
    operation_name: isString,
    service_name: isString,
    start_time_nanos: isNumber,
    end_time_nanos: isNumber,
    status: isSpanStatus,
    attributes: isNullableString,
    exception_type: isNullableString,
    exception_message: isNullableString,
    exception_stack_trace: isNullableString,
  },
  [EVENT_TYPE.SNAPSHOT]: {
    id: isNumber,
    test_id: isString,
    system: isString,
    state_json: isString,
    summary: isString,
    captured_at: isNullableString,
    trigger: isString,
  },
  [EVENT_TYPE.MOCK_INTERACTION]: {
    id: isNumber,
    test_id: isNullableString,
    timestamp: isString,
    system: isString,
    protocol: isString,
    method: isString,
    target: isString,
    matched: isBoolean,
    stub_id: isNullableString,
    attribution: isString,
    request_body: isNullableString,
    request_body_truncated: isBoolean,
    response_body: isNullableString,
    response_body_truncated: isBoolean,
    status: isString,
    latency_ms: isNullableNumber,
    near_misses: isStringArray,
    trace_id: isNullableString,
    scenario_name: isNullableString,
    scenario_state: isNullableString,
    next_scenario_state: isNullableString,
    configured_delay_ms: isNullableNumber,
    fault: isNullableString,
    client_deadline_ms: isNullableNumber,
  },
  [EVENT_TYPE.MOCK_WARNING]: {
    id: isNumber,
    test_id: isNullableString,
    timestamp: isString,
    system: isString,
    kind: isString,
    message: isString,
    stub_id: isNullableString,
    target: isNullableString,
  },
} satisfies { [Type in EventType]: ObjectSchema<LivePayloads[Type]> };
