"""
mkdocs-macros module: YAML data layer for Stove docs.

- Reads docs/_data/{frameworks,runtimes,tests,systems,observability}/*.yaml
- Writes the merged canonical docs/assets/data/setup.json at build time so the
  wizard + cookbook keep working without manual conversion.
- Exposes the same data to Jinja under: stove.frameworks, stove.systems, etc.

Jinja usage in any .md page (when macros plugin is enabled):

    {% for id, sys in stove.systems.items() %}
      - **{{ sys.label }}** (`{{ id }}`) family={{ sys.family }}
    {% endfor %}

Helpers:

    {{ wizard_link(sys="postgresql,kafka", mk="wiremock", label="open in wizard") }}
"""

from __future__ import annotations

import json
from pathlib import Path

import yaml


def _read_bucket(data_dir: Path, bucket: str, prefix: str = "") -> dict:
    out: dict = {}
    bdir = data_dir / bucket
    if not bdir.is_dir():
        return out
    for f in sorted(bdir.glob("*.yaml")):
        with f.open("r", encoding="utf-8") as fh:
            entry = yaml.safe_load(fh)
        if entry is None:
            continue
        key = f.stem
        full_key = f"{prefix}{key}" if prefix else key
        out[full_key] = entry
    return out


def _load(docs_dir: Path) -> dict:
    data_dir = docs_dir / "_data"
    return {
        "frameworks":    _read_bucket(data_dir, "frameworks"),
        "runtimes":      _read_bucket(data_dir, "runtimes"),
        "tests":         _read_bucket(data_dir, "tests"),
        "systems":       _read_bucket(data_dir, "systems", prefix="sys."),
        "observability": _read_bucket(data_dir, "observability", prefix="obs."),
    }


def _emit_setup_json(docs_dir: Path, data: dict) -> Path:
    out = docs_dir / "assets" / "data" / "setup.json"
    out.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "$schema_note": (
            "Generated by hooks/macros.py from docs/_data/*.yaml. "
            "Edit YAML files, not this JSON."
        ),
        **data,
    }
    out.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    return out


def define_env(env):
    """mkdocs-macros entry point."""
    docs_dir = Path(env.conf["docs_dir"])
    data = _load(docs_dir)
    _emit_setup_json(docs_dir, data)

    # Expose merged data under `stove` namespace for Jinja
    env.variables["stove"] = data

    @env.macro
    def system(id: str) -> dict:
        """Look up a single entry across all buckets by id."""
        for bucket in ("systems", "observability", "frameworks", "runtimes", "tests"):
            if id in data.get(bucket, {}):
                return data[bucket][id]
        return {}

    @env.macro
    def system_label(id: str) -> str:
        e = system(id)
        return e.get("label", id) if e else id

    @env.macro
    def wizard_link(sys: str = "", mk: str = "", fw: str = "", label: str = "open in wizard") -> str:
        """Render an open-in-wizard anchor."""
        parts = ["<a class=\"open-in-wizard\""]
        if sys: parts.append(f' data-sys="{sys}"')
        if mk:  parts.append(f' data-mk="{mk}"')
        if fw:  parts.append(f' data-fw="{fw}"')
        parts.append(f">{label}</a>")
        return "".join(parts)

    @env.macro
    def gradle_dep(system_id: str) -> str:
        """Render testImplementation lines for a given system id (incl. sys./obs. prefixes)."""
        e = system(system_id)
        gradle = (e or {}).get("gradle") or []
        if not gradle:
            return ""
        block = "\n".join(f'    testImplementation("{g}")' for g in gradle)
        return f"```kotlin\n{block}\n```"
