"""
mkdocs-macros module: YAML data layer for Stove docs.

- Reads docs/_data/{frameworks,runtimes,tests,systems,observability}/*.yaml
- Writes the merged canonical docs/assets/data/setup.json at build time so the
  wizard + cookbook keep working without manual conversion.
- Exposes the same data to Jinja under: stove.frameworks, stove.systems, etc.

Jinja usage in any .md page (when macros plugin is enabled):

    {% for id, sys in stove.systems.items() %}
      - **{{ sys.label }}** (`{{ id }}`) family={{ sys.family }}
    {% endfor %}

Helpers:

    {{ wizard_link(sys="postgresql,kafka", mk="wiremock", label="open in wizard") }}
"""

from __future__ import annotations

import json
import re
from pathlib import Path

import yaml

_STALE_SNIPPET_PATTERNS = [
    (re.compile(r"com\.trendyol\.stove\.testing\.e2e\b"), "pre-0.20 package name"),
    (re.compile(r"\bContainerAppOptions\b"), "removed container runner API"),
    (re.compile(r"\bProcessAppOptions\b"), "removed process runner API"),
    (re.compile(r"\bGoAppOptions\b"), "removed Go runner API"),
    (re.compile(r"ReadinessStrategy\.HttpGet\s*\(\s*path\s*="), "HttpGet now requires a full url"),
    (re.compile(r"\bstove\s+serve\b"), "CLI now starts the dashboard with bare `stove`"),
    (re.compile(r"--port\s+8086\b"), "dashboard HTTP/MCP default port is now 4040"),
    (re.compile(r"\bcliPort\s*=\s*8086\b"), "DashboardSystemOptions.cliPort is the gRPC port, default 4041"),
]


def _walk_strings(value, path: str = ""):
    if isinstance(value, dict):
        for key, item in value.items():
            child = f"{path}.{key}" if path else str(key)
            yield from _walk_strings(item, child)
    elif isinstance(value, list):
        for index, item in enumerate(value):
            yield from _walk_strings(item, f"{path}[{index}]")
    elif isinstance(value, str):
        yield path, value


def _validate_setup_data(data: dict) -> None:
    errors = []
    for path, value in _walk_strings(data):
        for pattern, reason in _STALE_SNIPPET_PATTERNS:
            if pattern.search(value):
                errors.append(f"{path}: found /{pattern.pattern}/ ({reason})")

    if errors:
        joined = "\n  - ".join(errors)
        raise ValueError(f"Stale Stove docs snippet data:\n  - {joined}")


def _read_bucket(data_dir: Path, bucket: str, prefix: str = "") -> dict:
    out: dict = {}
    bdir = data_dir / bucket
    if not bdir.is_dir():
        return out
    for f in sorted(bdir.glob("*.yaml")):
        with f.open("r", encoding="utf-8") as fh:
            entry = yaml.safe_load(fh)
        if entry is None:
            continue
        key = f.stem
        full_key = f"{prefix}{key}" if prefix else key
        out[full_key] = entry
    return out


def _load(docs_dir: Path) -> dict:
    data_dir = docs_dir / "_data"
    return {
        "frameworks":    _read_bucket(data_dir, "frameworks"),
        "runtimes":      _read_bucket(data_dir, "runtimes"),
        "tests":         _read_bucket(data_dir, "tests"),
        "systems":       _read_bucket(data_dir, "systems", prefix="sys."),
        "observability": _read_bucket(data_dir, "observability", prefix="obs."),
    }


def _emit_setup_json(docs_dir: Path, data: dict) -> Path:
    out = docs_dir / "assets" / "data" / "setup.json"
    out.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "$schema_note": (
            "Generated by hooks/macros.py from docs/_data/*.yaml. "
            "Edit YAML files, not this JSON."
        ),
        **data,
    }
    out.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    return out


def define_env(env):
    """mkdocs-macros entry point."""
    docs_dir = Path(env.conf["docs_dir"])
    data = _load(docs_dir)
    _validate_setup_data(data)
    _emit_setup_json(docs_dir, data)

    # Expose merged data under `stove` namespace for Jinja
    env.variables["stove"] = data

    @env.macro
    def system(id: str) -> dict:
        """Look up a single entry across all buckets by id."""
        for bucket in ("systems", "observability", "frameworks", "runtimes", "tests"):
            if id in data.get(bucket, {}):
                return data[bucket][id]
        return {}

    @env.macro
    def system_label(id: str) -> str:
        e = system(id)
        return e.get("label", id) if e else id

    @env.macro
    def wizard_link(sys: str = "", mk: str = "", fw: str = "", label: str = "open in wizard") -> str:
        """Render an open-in-wizard anchor."""
        parts = ["<a class=\"open-in-wizard\""]
        if sys: parts.append(f' data-sys="{sys}"')
        if mk:  parts.append(f' data-mk="{mk}"')
        if fw:  parts.append(f' data-fw="{fw}"')
        parts.append(f">{label}</a>")
        return "".join(parts)

    @env.macro
    def gradle_dep(system_id: str) -> str:
        """Render testImplementation lines for a given system id (incl. sys./obs. prefixes)."""
        e = system(system_id)
        gradle = (e or {}).get("gradle") or []
        if not gradle:
            return ""
        block = "\n".join(f'    testImplementation("{g}")' for g in gradle)
        return f"```kotlin\n{block}\n```"
