FROM golang:1.26.2 AS build

WORKDIR /workspace
COPY go/stove-kafka ./go/stove-kafka
COPY recipes/process/golang/go-showcase ./recipes/process/golang/go-showcase

WORKDIR /workspace/recipes/process/golang/go-showcase
ARG GO_BUILD_FLAGS=""
RUN CGO_ENABLED=0 GOOS=linux go build ${GO_BUILD_FLAGS} -o /out/go-showcase .

FROM alpine:3.22
WORKDIR /app
COPY --from=build /out/go-showcase /app/go-showcase

EXPOSE 8090
ENTRYPOINT ["/app/go-showcase"]
