port: 8080
database:
  jdbcUrl: "jdbc:postgresql://localhost:5432/stove"
  host: "localhost"
  port: 1234
  name: "stove"
  username: ""
  password: ""

kafka:
  bootstrapServers: "localhost:9092"
  groupId: "test-group"
  clientId: "test-client"
  interceptorClasses: ["com.trendyol.stove.testing.e2e.standalone.kafka.intercepting.StoveKafkaBridge"]
  topics:
    product:
      topic: "product"
      retry: "product.retry"
      error: "product.error"

