// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: messages.proto

// buf:lint:ignore FILE_SAME_PACKAGE

package stoveobserver

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StoveKafkaObserverService_HealthCheck_FullMethodName           = "/com.trendyol.stove.kafka.StoveKafkaObserverService/healthCheck"
	StoveKafkaObserverService_OnConsumedMessage_FullMethodName     = "/com.trendyol.stove.kafka.StoveKafkaObserverService/onConsumedMessage"
	StoveKafkaObserverService_OnPublishedMessage_FullMethodName    = "/com.trendyol.stove.kafka.StoveKafkaObserverService/onPublishedMessage"
	StoveKafkaObserverService_OnCommittedMessage_FullMethodName    = "/com.trendyol.stove.kafka.StoveKafkaObserverService/onCommittedMessage"
	StoveKafkaObserverService_OnAcknowledgedMessage_FullMethodName = "/com.trendyol.stove.kafka.StoveKafkaObserverService/onAcknowledgedMessage"
)

// StoveKafkaObserverServiceClient is the client API for StoveKafkaObserverService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StoveKafkaObserverServiceClient interface {
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	// buf:lint:ignore RPC_REQUEST_RESPONSE_UNIQUE
	OnConsumedMessage(ctx context.Context, in *ConsumedMessage, opts ...grpc.CallOption) (*Reply, error)
	// buf:lint:ignore RPC_REQUEST_RESPONSE_UNIQUE
	OnPublishedMessage(ctx context.Context, in *PublishedMessage, opts ...grpc.CallOption) (*Reply, error)
	// buf:lint:ignore RPC_REQUEST_RESPONSE_UNIQUE
	OnCommittedMessage(ctx context.Context, in *CommittedMessage, opts ...grpc.CallOption) (*Reply, error)
	// buf:lint:ignore RPC_REQUEST_RESPONSE_UNIQUE
	OnAcknowledgedMessage(ctx context.Context, in *AcknowledgedMessage, opts ...grpc.CallOption) (*Reply, error)
}

type stoveKafkaObserverServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStoveKafkaObserverServiceClient(cc grpc.ClientConnInterface) StoveKafkaObserverServiceClient {
	return &stoveKafkaObserverServiceClient{cc}
}

func (c *stoveKafkaObserverServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, StoveKafkaObserverService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stoveKafkaObserverServiceClient) OnConsumedMessage(ctx context.Context, in *ConsumedMessage, opts ...grpc.CallOption) (*Reply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Reply)
	err := c.cc.Invoke(ctx, StoveKafkaObserverService_OnConsumedMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stoveKafkaObserverServiceClient) OnPublishedMessage(ctx context.Context, in *PublishedMessage, opts ...grpc.CallOption) (*Reply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Reply)
	err := c.cc.Invoke(ctx, StoveKafkaObserverService_OnPublishedMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stoveKafkaObserverServiceClient) OnCommittedMessage(ctx context.Context, in *CommittedMessage, opts ...grpc.CallOption) (*Reply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Reply)
	err := c.cc.Invoke(ctx, StoveKafkaObserverService_OnCommittedMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stoveKafkaObserverServiceClient) OnAcknowledgedMessage(ctx context.Context, in *AcknowledgedMessage, opts ...grpc.CallOption) (*Reply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Reply)
	err := c.cc.Invoke(ctx, StoveKafkaObserverService_OnAcknowledgedMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StoveKafkaObserverServiceServer is the server API for StoveKafkaObserverService service.
// All implementations must embed UnimplementedStoveKafkaObserverServiceServer
// for forward compatibility.
type StoveKafkaObserverServiceServer interface {
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	// buf:lint:ignore RPC_REQUEST_RESPONSE_UNIQUE
	OnConsumedMessage(context.Context, *ConsumedMessage) (*Reply, error)
	// buf:lint:ignore RPC_REQUEST_RESPONSE_UNIQUE
	OnPublishedMessage(context.Context, *PublishedMessage) (*Reply, error)
	// buf:lint:ignore RPC_REQUEST_RESPONSE_UNIQUE
	OnCommittedMessage(context.Context, *CommittedMessage) (*Reply, error)
	// buf:lint:ignore RPC_REQUEST_RESPONSE_UNIQUE
	OnAcknowledgedMessage(context.Context, *AcknowledgedMessage) (*Reply, error)
	mustEmbedUnimplementedStoveKafkaObserverServiceServer()
}

// UnimplementedStoveKafkaObserverServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStoveKafkaObserverServiceServer struct{}

func (UnimplementedStoveKafkaObserverServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedStoveKafkaObserverServiceServer) OnConsumedMessage(context.Context, *ConsumedMessage) (*Reply, error) {
	return nil, status.Error(codes.Unimplemented, "method OnConsumedMessage not implemented")
}
func (UnimplementedStoveKafkaObserverServiceServer) OnPublishedMessage(context.Context, *PublishedMessage) (*Reply, error) {
	return nil, status.Error(codes.Unimplemented, "method OnPublishedMessage not implemented")
}
func (UnimplementedStoveKafkaObserverServiceServer) OnCommittedMessage(context.Context, *CommittedMessage) (*Reply, error) {
	return nil, status.Error(codes.Unimplemented, "method OnCommittedMessage not implemented")
}
func (UnimplementedStoveKafkaObserverServiceServer) OnAcknowledgedMessage(context.Context, *AcknowledgedMessage) (*Reply, error) {
	return nil, status.Error(codes.Unimplemented, "method OnAcknowledgedMessage not implemented")
}
func (UnimplementedStoveKafkaObserverServiceServer) mustEmbedUnimplementedStoveKafkaObserverServiceServer() {
}
func (UnimplementedStoveKafkaObserverServiceServer) testEmbeddedByValue() {}

// UnsafeStoveKafkaObserverServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StoveKafkaObserverServiceServer will
// result in compilation errors.
type UnsafeStoveKafkaObserverServiceServer interface {
	mustEmbedUnimplementedStoveKafkaObserverServiceServer()
}

func RegisterStoveKafkaObserverServiceServer(s grpc.ServiceRegistrar, srv StoveKafkaObserverServiceServer) {
	// If the following call panics, it indicates UnimplementedStoveKafkaObserverServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StoveKafkaObserverService_ServiceDesc, srv)
}

func _StoveKafkaObserverService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoveKafkaObserverServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoveKafkaObserverService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoveKafkaObserverServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoveKafkaObserverService_OnConsumedMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConsumedMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoveKafkaObserverServiceServer).OnConsumedMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoveKafkaObserverService_OnConsumedMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoveKafkaObserverServiceServer).OnConsumedMessage(ctx, req.(*ConsumedMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoveKafkaObserverService_OnPublishedMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishedMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoveKafkaObserverServiceServer).OnPublishedMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoveKafkaObserverService_OnPublishedMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoveKafkaObserverServiceServer).OnPublishedMessage(ctx, req.(*PublishedMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoveKafkaObserverService_OnCommittedMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommittedMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoveKafkaObserverServiceServer).OnCommittedMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoveKafkaObserverService_OnCommittedMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoveKafkaObserverServiceServer).OnCommittedMessage(ctx, req.(*CommittedMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoveKafkaObserverService_OnAcknowledgedMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcknowledgedMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoveKafkaObserverServiceServer).OnAcknowledgedMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoveKafkaObserverService_OnAcknowledgedMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoveKafkaObserverServiceServer).OnAcknowledgedMessage(ctx, req.(*AcknowledgedMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// StoveKafkaObserverService_ServiceDesc is the grpc.ServiceDesc for StoveKafkaObserverService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StoveKafkaObserverService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "com.trendyol.stove.kafka.StoveKafkaObserverService",
	HandlerType: (*StoveKafkaObserverServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "healthCheck",
			Handler:    _StoveKafkaObserverService_HealthCheck_Handler,
		},
		{
			MethodName: "onConsumedMessage",
			Handler:    _StoveKafkaObserverService_OnConsumedMessage_Handler,
		},
		{
			MethodName: "onPublishedMessage",
			Handler:    _StoveKafkaObserverService_OnPublishedMessage_Handler,
		},
		{
			MethodName: "onCommittedMessage",
			Handler:    _StoveKafkaObserverService_OnCommittedMessage_Handler,
		},
		{
			MethodName: "onAcknowledgedMessage",
			Handler:    _StoveKafkaObserverService_OnAcknowledgedMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "messages.proto",
}
