// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: messages.proto

// buf:lint:ignore FILE_SAME_PACKAGE

package stoveobserver

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthCheckResponse_ServingStatus int32

const (
	HealthCheckResponse_UNKNOWN         HealthCheckResponse_ServingStatus = 0
	HealthCheckResponse_SERVING         HealthCheckResponse_ServingStatus = 1
	HealthCheckResponse_NOT_SERVING     HealthCheckResponse_ServingStatus = 2
	HealthCheckResponse_SERVICE_UNKNOWN HealthCheckResponse_ServingStatus = 3 // Used only by the Watch method.
)

// Enum value maps for HealthCheckResponse_ServingStatus.
var (
	HealthCheckResponse_ServingStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "SERVING",
		2: "NOT_SERVING",
		3: "SERVICE_UNKNOWN",
	}
	HealthCheckResponse_ServingStatus_value = map[string]int32{
		"UNKNOWN":         0,
		"SERVING":         1,
		"NOT_SERVING":     2,
		"SERVICE_UNKNOWN": 3,
	}
)

func (x HealthCheckResponse_ServingStatus) Enum() *HealthCheckResponse_ServingStatus {
	p := new(HealthCheckResponse_ServingStatus)
	*p = x
	return p
}

func (x HealthCheckResponse_ServingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthCheckResponse_ServingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_messages_proto_enumTypes[0].Descriptor()
}

func (HealthCheckResponse_ServingStatus) Type() protoreflect.EnumType {
	return &file_messages_proto_enumTypes[0]
}

func (x HealthCheckResponse_ServingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthCheckResponse_ServingStatus.Descriptor instead.
func (HealthCheckResponse_ServingStatus) EnumDescriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{6, 0}
}

type ConsumedMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Message       []byte                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Topic         string                 `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	Partition     int32                  `protobuf:"varint,4,opt,name=partition,proto3" json:"partition,omitempty"`
	Offset        int64                  `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	Key           string                 `protobuf:"bytes,6,opt,name=key,proto3" json:"key,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,8,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumedMessage) Reset() {
	*x = ConsumedMessage{}
	mi := &file_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumedMessage) ProtoMessage() {}

func (x *ConsumedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumedMessage.ProtoReflect.Descriptor instead.
func (*ConsumedMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0}
}

func (x *ConsumedMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ConsumedMessage) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ConsumedMessage) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *ConsumedMessage) GetPartition() int32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *ConsumedMessage) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ConsumedMessage) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ConsumedMessage) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

type PublishedMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Message       []byte                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Topic         string                 `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	Key           string                 `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,5,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishedMessage) Reset() {
	*x = PublishedMessage{}
	mi := &file_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishedMessage) ProtoMessage() {}

func (x *PublishedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishedMessage.ProtoReflect.Descriptor instead.
func (*PublishedMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{1}
}

func (x *PublishedMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PublishedMessage) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *PublishedMessage) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *PublishedMessage) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PublishedMessage) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

type CommittedMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Partition     int32                  `protobuf:"varint,3,opt,name=partition,proto3" json:"partition,omitempty"`
	Offset        int64                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	Metadata      string                 `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommittedMessage) Reset() {
	*x = CommittedMessage{}
	mi := &file_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommittedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommittedMessage) ProtoMessage() {}

func (x *CommittedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommittedMessage.ProtoReflect.Descriptor instead.
func (*CommittedMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{2}
}

func (x *CommittedMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CommittedMessage) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *CommittedMessage) GetPartition() int32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *CommittedMessage) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *CommittedMessage) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

type AcknowledgedMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Partition     int32                  `protobuf:"varint,3,opt,name=partition,proto3" json:"partition,omitempty"`
	Offset        int64                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	Exception     string                 `protobuf:"bytes,5,opt,name=exception,proto3" json:"exception,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcknowledgedMessage) Reset() {
	*x = AcknowledgedMessage{}
	mi := &file_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcknowledgedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcknowledgedMessage) ProtoMessage() {}

func (x *AcknowledgedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcknowledgedMessage.ProtoReflect.Descriptor instead.
func (*AcknowledgedMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{3}
}

func (x *AcknowledgedMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AcknowledgedMessage) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *AcknowledgedMessage) GetPartition() int32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *AcknowledgedMessage) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *AcknowledgedMessage) GetException() string {
	if x != nil {
		return x.Exception
	}
	return ""
}

type Reply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reply) Reset() {
	*x = Reply{}
	mi := &file_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reply) ProtoMessage() {}

func (x *Reply) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reply.ProtoReflect.Descriptor instead.
func (*Reply) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{4}
}

func (x *Reply) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{5}
}

func (x *HealthCheckRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Status        HealthCheckResponse_ServingStatus `protobuf:"varint,1,opt,name=status,proto3,enum=com.trendyol.stove.kafka.HealthCheckResponse_ServingStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{6}
}

func (x *HealthCheckResponse) GetStatus() HealthCheckResponse_ServingStatus {
	if x != nil {
		return x.Status
	}
	return HealthCheckResponse_UNKNOWN
}

var File_messages_proto protoreflect.FileDescriptor

const file_messages_proto_rawDesc = "" +
	"\n" +
	"\x0emessages.proto\x12\x18com.trendyol.stove.kafka\"\xa7\x02\n" +
	"\x0fConsumedMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\amessage\x18\x02 \x01(\fR\amessage\x12\x14\n" +
	"\x05topic\x18\x03 \x01(\tR\x05topic\x12\x1c\n" +
	"\tpartition\x18\x04 \x01(\x05R\tpartition\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x03R\x06offset\x12\x10\n" +
	"\x03key\x18\x06 \x01(\tR\x03key\x12P\n" +
	"\aheaders\x18\b \x03(\v26.com.trendyol.stove.kafka.ConsumedMessage.HeadersEntryR\aheaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf3\x01\n" +
	"\x10PublishedMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\amessage\x18\x02 \x01(\fR\amessage\x12\x14\n" +
	"\x05topic\x18\x03 \x01(\tR\x05topic\x12\x10\n" +
	"\x03key\x18\x04 \x01(\tR\x03key\x12Q\n" +
	"\aheaders\x18\x05 \x03(\v27.com.trendyol.stove.kafka.PublishedMessage.HeadersEntryR\aheaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8a\x01\n" +
	"\x10CommittedMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x1c\n" +
	"\tpartition\x18\x03 \x01(\x05R\tpartition\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x03R\x06offset\x12\x1a\n" +
	"\bmetadata\x18\x05 \x01(\tR\bmetadata\"\x8f\x01\n" +
	"\x13AcknowledgedMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x1c\n" +
	"\tpartition\x18\x03 \x01(\x05R\tpartition\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x03R\x06offset\x12\x1c\n" +
	"\texception\x18\x05 \x01(\tR\texception\"\x1f\n" +
	"\x05Reply\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\".\n" +
	"\x12HealthCheckRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\"\xbb\x01\n" +
	"\x13HealthCheckResponse\x12S\n" +
	"\x06status\x18\x01 \x01(\x0e2;.com.trendyol.stove.kafka.HealthCheckResponse.ServingStatusR\x06status\"O\n" +
	"\rServingStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSERVING\x10\x01\x12\x0f\n" +
	"\vNOT_SERVING\x10\x02\x12\x13\n" +
	"\x0fSERVICE_UNKNOWN\x10\x032\xa1\x04\n" +
	"\x19StoveKafkaObserverService\x12l\n" +
	"\vhealthCheck\x12,.com.trendyol.stove.kafka.HealthCheckRequest\x1a-.com.trendyol.stove.kafka.HealthCheckResponse\"\x00\x12a\n" +
	"\x11onConsumedMessage\x12).com.trendyol.stove.kafka.ConsumedMessage\x1a\x1f.com.trendyol.stove.kafka.Reply\"\x00\x12c\n" +
	"\x12onPublishedMessage\x12*.com.trendyol.stove.kafka.PublishedMessage\x1a\x1f.com.trendyol.stove.kafka.Reply\"\x00\x12c\n" +
	"\x12onCommittedMessage\x12*.com.trendyol.stove.kafka.CommittedMessage\x1a\x1f.com.trendyol.stove.kafka.Reply\"\x00\x12i\n" +
	"\x15onAcknowledgedMessage\x12-.com.trendyol.stove.kafka.AcknowledgedMessage\x1a\x1f.com.trendyol.stove.kafka.Reply\"\x00b\x06proto3"

var (
	file_messages_proto_rawDescOnce sync.Once
	file_messages_proto_rawDescData []byte
)

func file_messages_proto_rawDescGZIP() []byte {
	file_messages_proto_rawDescOnce.Do(func() {
		file_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_messages_proto_rawDesc), len(file_messages_proto_rawDesc)))
	})
	return file_messages_proto_rawDescData
}

var file_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_messages_proto_goTypes = []any{
	(HealthCheckResponse_ServingStatus)(0), // 0: com.trendyol.stove.kafka.HealthCheckResponse.ServingStatus
	(*ConsumedMessage)(nil),                // 1: com.trendyol.stove.kafka.ConsumedMessage
	(*PublishedMessage)(nil),               // 2: com.trendyol.stove.kafka.PublishedMessage
	(*CommittedMessage)(nil),               // 3: com.trendyol.stove.kafka.CommittedMessage
	(*AcknowledgedMessage)(nil),            // 4: com.trendyol.stove.kafka.AcknowledgedMessage
	(*Reply)(nil),                          // 5: com.trendyol.stove.kafka.Reply
	(*HealthCheckRequest)(nil),             // 6: com.trendyol.stove.kafka.HealthCheckRequest
	(*HealthCheckResponse)(nil),            // 7: com.trendyol.stove.kafka.HealthCheckResponse
	nil,                                    // 8: com.trendyol.stove.kafka.ConsumedMessage.HeadersEntry
	nil,                                    // 9: com.trendyol.stove.kafka.PublishedMessage.HeadersEntry
}
var file_messages_proto_depIdxs = []int32{
	8, // 0: com.trendyol.stove.kafka.ConsumedMessage.headers:type_name -> com.trendyol.stove.kafka.ConsumedMessage.HeadersEntry
	9, // 1: com.trendyol.stove.kafka.PublishedMessage.headers:type_name -> com.trendyol.stove.kafka.PublishedMessage.HeadersEntry
	0, // 2: com.trendyol.stove.kafka.HealthCheckResponse.status:type_name -> com.trendyol.stove.kafka.HealthCheckResponse.ServingStatus
	6, // 3: com.trendyol.stove.kafka.StoveKafkaObserverService.healthCheck:input_type -> com.trendyol.stove.kafka.HealthCheckRequest
	1, // 4: com.trendyol.stove.kafka.StoveKafkaObserverService.onConsumedMessage:input_type -> com.trendyol.stove.kafka.ConsumedMessage
	2, // 5: com.trendyol.stove.kafka.StoveKafkaObserverService.onPublishedMessage:input_type -> com.trendyol.stove.kafka.PublishedMessage
	3, // 6: com.trendyol.stove.kafka.StoveKafkaObserverService.onCommittedMessage:input_type -> com.trendyol.stove.kafka.CommittedMessage
	4, // 7: com.trendyol.stove.kafka.StoveKafkaObserverService.onAcknowledgedMessage:input_type -> com.trendyol.stove.kafka.AcknowledgedMessage
	7, // 8: com.trendyol.stove.kafka.StoveKafkaObserverService.healthCheck:output_type -> com.trendyol.stove.kafka.HealthCheckResponse
	5, // 9: com.trendyol.stove.kafka.StoveKafkaObserverService.onConsumedMessage:output_type -> com.trendyol.stove.kafka.Reply
	5, // 10: com.trendyol.stove.kafka.StoveKafkaObserverService.onPublishedMessage:output_type -> com.trendyol.stove.kafka.Reply
	5, // 11: com.trendyol.stove.kafka.StoveKafkaObserverService.onCommittedMessage:output_type -> com.trendyol.stove.kafka.Reply
	5, // 12: com.trendyol.stove.kafka.StoveKafkaObserverService.onAcknowledgedMessage:output_type -> com.trendyol.stove.kafka.Reply
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_messages_proto_init() }
func file_messages_proto_init() {
	if File_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_messages_proto_rawDesc), len(file_messages_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_messages_proto_goTypes,
		DependencyIndexes: file_messages_proto_depIdxs,
		EnumInfos:         file_messages_proto_enumTypes,
		MessageInfos:      file_messages_proto_msgTypes,
	}.Build()
	File_messages_proto = out.File
	file_messages_proto_goTypes = nil
	file_messages_proto_depIdxs = nil
}
