quarkus.console.enabled=false
quarkus.class-loading.parent-first-artifacts=org.apache.kafka:kafka-clients
quarkus.http.port=8080
quarkus.datasource.db-kind=postgresql
quarkus.datasource.devservices.enabled=false
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/stove
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.flyway.migrate-at-start=true

kafka.bootstrap.servers=localhost:9092
app.kafka.bridge-interceptor-class=
mp.messaging.incoming.product-create.connector=smallrye-kafka
mp.messaging.incoming.product-create.topic=trendyol.stove.service.product.create.0
mp.messaging.incoming.product-create.group.id=stove-quarkus-example
mp.messaging.incoming.product-create.value.deserializer=stove.quarkus.example.infrastructure.kafka.CreateProductCommandDeserializer
mp.messaging.incoming.product-create.kafka-configuration=product-create
mp.messaging.outgoing.product-created.connector=smallrye-kafka
mp.messaging.outgoing.product-created.topic=trendyol.stove.service.product.created.0
mp.messaging.outgoing.product-created.value.serializer=stove.quarkus.example.infrastructure.kafka.ProductCreatedEventSerializer
mp.messaging.outgoing.product-created.kafka-configuration=product-created

clients.supplier.url=http://localhost:7078
